// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/diseaz-joom/play-wire/boxes/b"
	"github.com/diseaz-joom/play-wire/boxes/c"
	"github.com/diseaz-joom/play-wire/boxes/e"
	"github.com/diseaz-joom/play-wire/boxes/g"
)

// Injectors from wire.go:

func MakeService() *g.Box {
	box := b.MakeBox()
	cBox := c.MakeBox()
	eBox := e.MakeBox(box, cBox)
	gBox := g.MakeBox(eBox)
	return gBox
}
