// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/diseaz-joom/play-wire/boxes/a"
	"github.com/diseaz-joom/play-wire/boxes/b"
	"github.com/diseaz-joom/play-wire/boxes/c"
	"github.com/diseaz-joom/play-wire/boxes/d"
	"github.com/diseaz-joom/play-wire/boxes/e"
	"github.com/diseaz-joom/play-wire/boxes/f"
	"github.com/diseaz-joom/play-wire/boxes/g"
	"github.com/diseaz-joom/play-wire/svc/one"
)

// Injectors from wire.go:

func MakeService() *one.Service {
	box := a.MakeBox()
	bBox := b.MakeBox()
	dBox := d.MakeBox(box, bBox)
	cBox := c.MakeBox()
	eBox := e.MakeBox(bBox, cBox)
	fBox := f.MakeBox(dBox, eBox)
	gBox := g.MakeBox(eBox)
	service := &one.Service{
		F: fBox,
		G: gBox,
	}
	return service
}
